services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    #volumes:
    #  - ./volumes/minio:/data  # causes deadlock errors when using put_object
    command: server /data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0" # https://medium.com/%40luketn/java-on-docker-sigill-exception-on-mac-os-sequoia-15-2-9311e4775442
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/var/lib/neo4j/import
      - ./volumes/neo4j/plugins:/plugins

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./volumes/qdrant:/qdrant/storage

  isolated-jupyter-kernel:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      secrets:
        - git_token
    environment:
      - JUPYTER_SESSIONS_DIR=/mnt/jupyter_sessions
    volumes:
      - ./jupyter_sessions:/mnt/jupyter_sessions
    ports:
      - 5200:5000
    restart: unless-stopped

  katex-validator:
    build:
      context: .
      dockerfile: Dockerfile.katex
      secrets:
        - git_token
    ports:
      - 3000:3000
    restart: unless-stopped

configs:
  qdrant_config:
    content: |
      log_level: INFO

secrets:
  git_token:
    file: ./git_token.txt 